name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Use Docker Image
        run: |
          # docker-compose up
          docker run -d -p 8080:8080 -v $(pwd)/tiddlywiki:/app oeyoews/tiddlywiki:latest --build index