name: release-and-page
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    # paths-ignore:
    # - 'README.md'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

concurrency:
  group: release-ci-group
  cancel-in-progress: false

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release-and-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install Dependency
        run: |
          # yarn install --production
          yarn workspaces focus --all --production
          # sudo apt-get install libimagequant
          # npm install -g pngquant-bin && pngquant

      - name: Build Neotw
        run: |
          npm run build:neotw

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./dist

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
